[package]
edition.workspace    = true
license.workspace    = true
name                 = "unavi-wasm-compat"
publish              = false
repository.workspace = true
version.workspace    = true

[lints]
workspace = true

[dependencies]
n0-future.workspace = true

[target.'cfg(not(target_family = "wasm"))'.dependencies]
tokio = { features = ["rt", "time"], workspace = true }
