[package]
edition.workspace    = true
license.workspace    = true
name                 = "wired-ecs"
publish              = false
repository.workspace = true
version.workspace    = true

[lints]
workspace = true

[dependencies]
bytemuck.workspace    = true
postcard.workspace    = true
serde.workspace       = true
wired-ecs-derive.path = "../../crates/wired-ecs-derive"
wit-bindgen.workspace = true
