[package]
edition.workspace    = true
license.workspace    = true
name                 = "wired-data-store"
publish              = false
repository.workspace = true
version.workspace    = true

[lints]
workspace = true

[dependencies]
anyhow.workspace  = true
cid               = "0.11.1"
flume.workspace   = true
getrandom         = "0.3.4"
iroh              = "0.95.1"
jose-jwk          = "0.1.2"
loro              = "1.10.3"
multihash         = "0.19.3"
p256              = { features = ["ecdsa"], version = "0.13.2" }
rand.workspace    = true
ring              = "0.17.14"
sha2              = "0.10.9"
signature         = "2.2.0"
smol_str          = "0.3.4"
sqlx              = { features = ["runtime-tokio", "sqlite"], version = "0.8.6" }
thiserror         = "2.0.17"
tokio.workspace   = true
tracing.workspace = true
xdid.workspace    = true

[dev-dependencies]
tempfile.workspace = true
tokio              = { features = ["macros", "rt-multi-thread"], workspace = true }
