[package]
edition.workspace    = true
license.workspace    = true
name                 = "wired-data-store"
publish              = false
repository.workspace = true
version.workspace    = true

[package.metadata.sqlx]
offline = true

[lints]
workspace = true

[dependencies]
anyhow.workspace  = true
cid               = "0.11.1"
getrandom         = "0.3.4"
loro              = "1.10.3"
multihash         = "0.19.3"
sha2              = "0.10.9"
smol_str          = "0.3.4"
sqlx              = { features = ["runtime-tokio", "sqlite"], version = "0.8.6" }
tokio.workspace   = true
tracing.workspace = true

[dev-dependencies]
tempfile.workspace = true
tokio              = { features = ["macros", "rt-multi-thread"], workspace = true }
