[package]
name = "unavi-world-server"
publish = false
version.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
capnp-rpc.workspace = true
capnp.workspace = true
dwn.workspace = true
thiserror.workspace = true
tokio.workspace = true
tracing.workspace = true
wired-social = { path = "../wired-social" }
wired-world = { path = "../wired-world" }
wtransport.workspace = true
xwt-core.workspace = true
xwt-futures-io = { path = "../xwt-futures-io" }
xwt-wtransport.workspace = true
