[package]
edition.workspace    = true
license.workspace    = true
name                 = "wired-cli"
publish              = false
repository.workspace = true
version.workspace    = true

[lints]
workspace = true

[dependencies]
anyhow.workspace      = true
clap.workspace        = true
directories.workspace = true
dwn.workspace         = true
serde_json.workspace  = true
tokio                 = { features = ["macros", "rt", "rt-multi-thread"], workspace = true }
tracing.workspace     = true
tracing-subscriber    = { features = ["env-filter"], workspace = true }
unavi-constants.path  = "../unavi-constants"
wired-protocol.path   = "../wired-protocol"
xdid.workspace        = true
zeroize.workspace     = true
