[package]
name = "unavi-social-server"
version.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true

[dependencies]
axum-server.workspace = true
dwn-server = "0.0.9"
dwn.workspace = true
tracing.workspace = true
