[package]
name = "unavi-system"
version.workspace = true
edition.workspace = true
repository.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
wit-bindgen-rt.workspace = true

[package.metadata.component]
package = "unavi:system"

[package.metadata.component.target.dependencies]
"wired:gltf" = { path = "../../wired-protocol/spatial/wit/wired-gltf" }
"wired:log" = { path = "../../wired-protocol/spatial/wit/wired-log" }
"wired:math" = { path = "../../wired-protocol/spatial/wit/wired-math" }
"wired:script" = { path = "../../wired-protocol/spatial/wit/wired-script" }
